name: deploy-prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_ALAJI }}
          username: ${{ secrets.SSH_USER_ALAJI }}
          password: ${{ secrets.SSH_PASSWORD_ALAJI }}
          port: ${{ secrets.SSH_PORT_ALAJI }}
          script: |
            cd /var/www/html/page_html
            git fetch 
            git pull origin main
